// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWiJGlbtnr_Hag6n_nD7WxvSVVRJbN5yY',
    appId: '1:47249146398:web:0818d718905030d94d640f',
    messagingSenderId: '47249146398',
    projectId: 'qh-internship-assignment',
    authDomain: 'qh-internship-assignment.firebaseapp.com',
    storageBucket: 'qh-internship-assignment.appspot.com',
    measurementId: 'G-VRZ72RF257',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnM9JT8Bp88KiOyheuNSfc__aLpYhMd3Y',
    appId: '1:47249146398:android:dc4f8d87afc977034d640f',
    messagingSenderId: '47249146398',
    projectId: 'qh-internship-assignment',
    storageBucket: 'qh-internship-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB09KxGA5fOZOceXiNvsZAVE3IgNm_-miw',
    appId: '1:47249146398:ios:260c5eddbd5fc44f4d640f',
    messagingSenderId: '47249146398',
    projectId: 'qh-internship-assignment',
    storageBucket: 'qh-internship-assignment.appspot.com',
    iosBundleId: 'com.example.flutterInternshipAsignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB09KxGA5fOZOceXiNvsZAVE3IgNm_-miw',
    appId: '1:47249146398:ios:260c5eddbd5fc44f4d640f',
    messagingSenderId: '47249146398',
    projectId: 'qh-internship-assignment',
    storageBucket: 'qh-internship-assignment.appspot.com',
    iosBundleId: 'com.example.flutterInternshipAsignment',
  );
}
